### ISSUE TITLE
0.2.4 does not run when it is called from CommonJS

### ISSUE THREAD

**Issue by tksst** [egoist/load-tsconfig#23]
This code works fine on v0.2.3, but does not run on v0.2.4:

```
const { loadTsConfig } = require("load-tsconfig");

const loaded = loadTsConfig(".")
console.log(JSON.stringify(loaded, undefined, "   "));
```

Error log:
```
node:internal/modules/cjs/loader:1373
    throw new ERR_INVALID_ARG_VALUE('filename', filename, createRequireError);
    ^

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at createRequire (node:internal/modules/cjs/loader:1373:11)
    at Object.<anonymous> (/workspaces/dev/load-tsconfig-bug/node_modules/load-tsconfig/dist/index.cjs:139:107)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/workspaces/dev/load-tsconfig-bug/index.cjs:3:26) {
  code: 'ERR_INVALID_ARG_VALUE'
}
```

This seems to be because `dist/index.cjs' lines 138-139 are weird:

```
// src/index.ts
var import_meta = {};
var req = typeof globalThis.require === "function" ? globalThis.require : (0, import_module.createRequire)(import_meta.url);
```

Also note that this bug breaks tsup.

**Comment by egoist** [comment]
fixed in 0.2.5
